### ISSUE TITLE
 chrome_driver_path None

### ISSUE THREAD

**Issue by nedz14** [itaybia/kissanime_py_downloader#1]
C:\webdrivers>url_fetcher.exe -user xxxx -pass xxxxxx -url http://kissanime.ru/Anime/Haikyuu-Second-Season -firs
t 001 -last 025 -rename -out C:\Users\user\Downloads\Documents
 output_folder C:\Users\user\Downloads\Documents
 chrome_driver_path None
 series_url http://kissanime.ru/Anime/Haikyuu-Second-Season
 user_name 
 password 
 first_index 1
 last_index 25
 rename_files True
Traceback (most recent call last):
  File "<string>", line 153, in <module>
  File "genericpath.py", line 18, in exists
TypeError: coercing to Unicode: need string or buffer, NoneType found
url_fetcher returned -1

win7 64bit
i v placed chromedriver in path.

**Comment by itaybia** [comment]
right, i see i forgot to write that the chrome driver is mandatory as part of the command.
please add: -chrome_drv < path to chromedriver.exe >
(and you should probably edit your issue and remove the user/password so others won't see them).

let me know if that works.

**Comment by nedz14** [comment]
Hello again, thanks for your response.
i got an HTML and text file both empty.
https://pastebin.com/AmNSHW6j

**Comment by itaybia** [comment]
hi,
can you please help me debug your issue? on my pc it seems to work fine.
first up, if you enter the link [here](http://kissanime.ru/Anime/Wolf-s-Rain/Episode-002?id=8812&s=rapidvideo)
can you see the "CLICK HERE TO DOWNLOAD" button at the bottom? (after you log into the site).
in your log i see it extracts this link, but apparently doesn't see the button. this makes me believe the login failed or something of the sort.

run using this [exe](https://github.com/itaybia/kissanime_py_downloader/releases/download/v1.0.2/url_fetcher.exe)

**Comment by nedz14** [comment]
thank you itaybia and sorry because it was may fault, i used my older password.
Now it work like  a charm.
keep up the great  work
bless.

**Comment by itaybia** [comment]
Great! Good to know.
________________________________
